Apps/core/urls.py
from django.urls import path
from Apps.core.views.dashboard.views import DashboardView
from Apps.core.views.driver.views import  DriverListView, DriverCreateView, DriverDeleteView, DriverUpdateView
from Apps.core.views.ticket.views import TicketCreateView, TicketDeleteView, TicketListView, TicketUpdateView
from Apps.core.views.purchase.views import PurchaseCreateView, PurchaseListView, PurchaseDeleteView, PurchaseUpdateView

app_name = 'core'

urlpatterns = [
    # Home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    # Ticket
    path('ticket/list/', TicketListView.as_view(), name='ticket_list'),
    path('ticket/add/', TicketCreateView.as_view(), name='ticket_create'),
    path('ticket/update/<int:pk>/', TicketUpdateView.as_view(), name='ticket_update'),
    path('ticket/delete/<int:pk>/', TicketDeleteView.as_view(), name='ticket_delete'),

    # Driver
    path('driver/list/', DriverListView.as_view(), name='driver_list'),
    path('driver/add/', DriverCreateView.as_view(), name='driver_create'),
    path('driver/update/<int:pk>/', DriverUpdateView.as_view(), name='driver_update'),
    path('driver/delete/<int:pk>/', DriverDeleteView.as_view(), name='driver_delete'),

    # Purchase
    path('purchase/list/', PurchaseListView.as_view(), name='purchase_list'),
    path('purchase/add/', PurchaseCreateView.as_view(), name='purchase_create'),
    path('purchase/update/<int:pk>/', PurchaseUpdateView.as_view(), name='purchase_update'),
    path('purchase/delete/<int:pk>/', PurchaseDeleteView.as_view(), name='purchase_delete'),
]

Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static

from Apps.security.views.dashboard.views import page_not_found404

urlpatterns = [
    path('', include('Apps.login.urls')),
    path('login/', include('Apps.login.urls')),
    path('menu/', include('Apps.core.urls')),
    path('user/', include('Apps.user.urls')),
    path('config/', include('Apps.security.urls')),
    path('admin/', admin.site.urls),
]

handler404 = page_not_found404

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/core/models.py
from datetime import datetime
from datetime import timedelta 

from django.db import models
from django.forms import model_to_dict
from django.conf import settings

from crum import get_current_user
from simple_history.models import HistoricalRecords

from Apps.utils import gender_choices
from Apps.models import BaseModel
from Apps.security.validators import validate_file_size

class Ticket(BaseModel):
    name = models.CharField(max_length=150, verbose_name='Nombre', unique=True)
    price = models.DecimalField(default=1.00, max_digits=9, decimal_places=2, verbose_name='Precio')

    def __str__(self):
        return self.name
    
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        user = get_current_user()
        if user is not None and str(user) != 'AnonymousUser':
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        self.full_clean()
        super(Ticket, self).save(force_insert, force_update, using, update_fields)

    def toJSON(self):
        item = model_to_dict(self)
        item['price'] = format(self.price, '.2f')
        date_creation = self.date_creation - timedelta(hours=5)
        item['user_create'] = self.user_creation.toJSON()
        item['date_create'] = date_creation.strftime('%d/%m/%Y %H:%M')
        item['date_update'] = '-'
        item['user_update'] = {'full_name': '-'}
        if self.user_updated:
            date_updated = self.date_updated - timedelta(hours=5)
            item['date_update'] = date_updated.strftime('%d/%m/%Y %H:%M')
            item['user_update'] = self.user_updated.toJSON()
        return item

    class Meta:
        verbose_name = 'Ticket'
        verbose_name_plural = 'Tickets'
        ordering = ['id']

class Driver(BaseModel):
    names = models.CharField(max_length=150, verbose_name='Nombres')
    surnames = models.CharField(max_length=150, verbose_name='Apellidos')
    dni = models.CharField(max_length=8, verbose_name='Dni', unique=True)
    date_birthday = models.DateField(default=datetime.now, verbose_name='Fecha de nacimiento')
    address = models.CharField(max_length=150, null=True, blank=True, verbose_name='Dirección')
    gender = models.CharField(max_length=10, choices=gender_choices, default='male', verbose_name='Sexo')
    history = HistoricalRecords()

    def __str__(self):
        return self.get_full_name()
    
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        user = get_current_user()
        if user is not None and str(user) != 'AnonymousUser':
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        self.full_clean()
        super(Driver, self).save(force_insert, force_update, using, update_fields)

    def get_full_name(self):
        return '{} {}'.format(self.names, self.surnames)

    def toJSON(self):
        item = model_to_dict(self)
        item['gender'] = {'id': self.gender, 'name': self.get_gender_display()}
        item['date_birthday'] = self.date_birthday.strftime('%d/%m/%Y')
        item['full_name'] = self.get_full_name()
        date_creation = self.date_creation - timedelta(hours=5)
        item['user_create'] = self.user_creation.toJSON()
        item['date_create'] = date_creation.strftime('%d/%m/%Y %H:%M')
        item['date_update'] = (self.date_updated - timedelta(hours=5)).strftime('%d/%m/%Y %H:%M') if self.user_updated else '-'
        item['user_update'] = self.user_updated.toJSON() if self.user_updated else {'username': '-', 'full_name': '-'}
        return item

    class Meta:
        verbose_name = 'Driver'
        verbose_name_plural = 'Drivers'
        ordering = ['id']

class Purchase(BaseModel):
    driv = models.ForeignKey(Driver, on_delete=models.PROTECT, verbose_name='Chofer Asociado')
    date_joined = models.DateField(default=datetime.now, verbose_name='Fecha Compra')
    file = models.FileField(upload_to='files', null=True, blank=True, validators=[validate_file_size], verbose_name='Documento')
    history = HistoricalRecords()
    
    def __str__(self):
        return self.driv.names
    
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        user = get_current_user()
        if user is not None and str(user) != 'AnonymousUser':
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        self.full_clean()
        super(Purchase, self).save(force_insert, force_update, using, update_fields)
    
    def get_file(self):
        if self.file:
            return '{}{}'.format(settings.MEDIA_URL, self.file)
        return '{}{}'.format(settings.STATIC_URL, 'img/FileEmpty.pdf')

    def toJSON(self):
        item = model_to_dict(self)
        item['driv'] = self.driv.toJSON()
        item['file'] = self.get_file()
        item['date_joined'] = self.date_joined.strftime('%d/%m/%Y')
        item['det'] = [i.toJSON() for i in self.detpurchase_set.all()]
        date_creation = self.date_creation - timedelta(hours=5)
        item['user_create'] = self.user_creation.toJSON()
        item['date_create'] = date_creation.strftime('%d/%m/%Y %H:%M')
        item['date_update'] = '-'
        item['user_update'] = {'full_name': '-'}
        if self.user_updated:
            date_updated = self.date_updated - timedelta(hours=5)
            item['date_update'] = date_updated.strftime('%d/%m/%Y %H:%M')
            item['user_update'] = self.user_updated.toJSON()
        return item

    def delete(self, using=None, keep_parents=False):
        for det in self.detpurchase_set.all():
            det.prod.save()
        super(Purchase, self).delete()

    class Meta:
        verbose_name = 'Purchase'
        verbose_name_plural = 'Purchases'
        ordering = ['-id'] 

class DetPurchase(BaseModel):
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)
    prod = models.ForeignKey(Ticket, on_delete=models.PROTECT, verbose_name='Ticket')
    cant = models.IntegerField(default=0, verbose_name='Cantidad')
    serieinicial = models.IntegerField(default=0, verbose_name='SerieInicial')
    seriefinal = models.IntegerField(default=0, verbose_name='SerieFinal')
    history = HistoricalRecords()

    def __str__(self):
        return self.prod.name
    
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        user = get_current_user()
        if user is not None and str(user) != 'AnonymousUser':
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        self.full_clean()
        super(DetPurchase, self).save(force_insert, force_update, using, update_fields)

    def toJSON(self):
        item = model_to_dict(self, exclude=['purchase'])
        item['prod'] = self.prod.toJSON()
        return item

    class Meta:
        verbose_name = 'Purchase Detail'
        verbose_name_plural = 'Purchases Details'
        ordering = ['id']

Apps/core/views/dashboard/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class DashboardView(LoginRequiredMixin,TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        # now = datetime.now().strftime('%Y-%m-%d')
        # create_purchases = Purchase.objects.filter(date_joined=now).count()
        # active_users = User.objects.all().count()
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Panel de administrador'
        # context['users'] = active_users
        # context['registro'] = create_purchases
        return context

Apps/core/views/driver/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
# from django.utils.decorators import method_decorator
# from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from Apps.core.forms import DriverForm
from Apps.security.mixins import ValidatePermissionRequiredMixin
from Apps.core.models import Driver

class DriverListView(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    model = Driver
    template_name = 'driver/list.html'
    permission_required = 'view_driver'

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                position = 1
                for i in Driver.objects.all():
                    item = i.toJSON()
                    item['position'] = position
                    data.append(item)
                    position += 1
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Choferes'
        context['create_url'] = reverse_lazy('core:driver_create')
        context['list_url'] = reverse_lazy('core:driver_list')
        context['entity'] = 'Drivers'
        return context

class DriverCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Driver
    form_class = DriverForm
    template_name = 'driver/create.html'
    success_url = reverse_lazy('core:driver_list')
    permission_required = 'add_driver'
    url_redirect = success_url

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción.'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación de Chofer'
        context['entity'] = 'Drivers'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        return context

class DriverUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Driver
    form_class = DriverForm
    template_name = 'driver/create.html'
    success_url = reverse_lazy('core:driver_list')
    permission_required = 'change_driver'
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción.'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición de un Chofer'
        context['entity'] = 'Drivers'
        context['list_url'] = self.success_url
        context['action'] = 'edit'
        return context

class DriverDeleteView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DeleteView):
    model = Driver
    template_name = 'driver/delete.html'
    success_url = reverse_lazy('core:driver_list')
    permission_required = 'delete_driver'
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de un Chofer'
        context['entity'] = 'Drivers'
        context['list_url'] = self.success_url
        return context

Apps/core/templates/purchase/create.html
{% extends 'list.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head_list %}
    <link href="{% static 'lib/select2-4.1.0/css/select2.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'lib/select2-4.1.0/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/select2-4.1.0/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/select2-4.1.0/js/i18n/es.js' %}"></script>

    <link href="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.js' %}"></script>

    <script src="{% static 'purchase/js/form.js' %}"></script>
{% endblock %}

{% block content %} 
    
    <form id="frmPurchase" enctype="multipart/form-data" method="post">
        <div class="card">
            <div class="card-header navbar-dark-blue">
                <h3 class="card-title fuente">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}
                    {{ title }}
                </h3>
            </div>
            <div id="loading-indicator">
                <div class="card-body">
                    <div class="row preloader-row">
                        <div class="preloader-form"></div>
                    </div>
                </div>
                <div class="card-footer"></div>
            </div>
            <div id="main-form">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="card card-secondary">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fas fa-boxes"></i> Detalle de boletos</h3>
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label>Buscador de boletos:</label>
                                        <div class="input-group">
                                            <select class="form-control select2" name="search"></select>
                                        </div>
                                    </div>
                                    <hr>
                                    <button type="button" class="btn btn-danger btn-xs btn-flat btn-custom btnRemoveAll">
                                        <i class="fas fa-trash"></i> Eliminar todos mis registros
                                    </button>
                                    <hr>
                                    <table class="table table-bordered" id="tblProducts">
                                        <thead>
                                        <tr>
                                            <th>Eliminar</th>
                                            <th>Boleto</th>
                                            <th>Cantidad</th>
                                            <th>Serie Inicial</th>
                                            <th>Serie Final</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="card card-secondary">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fas fa-file-invoice"></i> Datos de la Compra</h3>
                                </div>
                                <div class="card-body">
                                    <input type="hidden" name="action" value="{{ action }}">
                                    <div class="form-group">
                                        <label>Fecha de compra:</label>
                                        {{ form.date_joined }}
                                    </div>
                                    <div class="form-group">
                                        <label>Chofer:</label>
                                        <div class="input-group">
                                            {{ form.driv }}
                                            <div class="input-group-append">
                                                <button class="btn btn-success btn-flat btnAddDriver" type="button">
                                                    <i class="fas fa-user-plus"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group custom-file-div">
                                        <label>Documento:</label>
                                        <label for="id_file" class="custom-file-upload">
                                            <i class="fa-solid fa-paperclip"></i>
                                            Subir archivo
                                        </label>
                                        <!-- {{ form.file|add_class:'custom-file-input' }} -->
                                        <input type="file" name="{{ form.file.name }}" class="custom-file-input" id="id_file">
                                        <span id="file-path"></span>
                                        {% if form.file.value %}
                                            <div>
                                                Actualmente: 
                                                <a href="{{ form.file.value.url }}" target="_blank">{{ form.file.value.name }}</a>
                                            </div>
                                            <div class="custom-checkbox">
                                                <input type="checkbox" name="file-clear" id="file-clear_id">
                                                <label for="file-clear_id">Limpiar</label>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-flat btn-custom">
                        <i class="fas fa-save"></i> 
                        {% if action == 'add' %}
                            Agregar registro
                        {% else %}
                            Guardar registro
                        {% endif %}
                    </button>
                    <a href="{{ list_url }}" class="btn btn-danger btn-flat btn-custom">
                        <i class="fas fa-times"></i> Cancelar
                    </a>
                </div>
            </div>
        </div>
    </form>

    <!-- Modal Driver -->
    <div class="modal fade" id="myModalDriver" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <form id="frmDriver" enctype="multipart/form-data" method="post">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">
                            <b><i class="fas fa-user-plus"></i> Nuevo registro de un chofer</b>
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {% for field in frmDriver.visible_fields %}
                            <div class="form-group">
                                <label for="email">{{ field.label }}:</label>
                                {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary btn-block btn-flat btn-custom">
                            <i class="fas fa-save"></i> Guardar Chofer
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>   
    <!-- <script>
        purchases.items.products = {{ det|safe }};
    </script> -->
{% endblock %}

Apps/core/templates/purchase/delete.html
{% extends 'delete.html' %}

{% block messagedelete %}
    Se va eliminar la compra N° "{{ object.id }}" de manera permanente.
{% endblock %}

Apps/core/templates/purchase/list.html
{% extends 'list.html' %}
{% load static %}
{% block head_list %}
    <script src="{% static 'purchase/js/list.js' %}"></script>
{% endblock %}

{% block columns %}
    <tr>
        <th scope="col" style="width: 9%;">Nro</th>
        <th scope="col" style="width: 25%;">Chofer</th>
        <th scope="col" style="width: 15%;">Fec. Registro</th>
        <th scope="col" style="width: 18%;">Fec. Creación</th>
        <th scope="col" style="width: 18%;">Fec. Actualización</th>
        <th scope="col" style="width: 15%;">Opciones</th>
    </tr>
{% endblock %}

{% block javascript %}
    <div class="modal fade" id="ModalPurchaseDet" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b><i class="fas fa-file-invoice"></i> Consulta de
                        detalle de boletos</b></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table class="table table-bordered" id="tblDet">
                        <thead>
                        <tr>
                            <th>Tipo de Boleto</th>
                            <th>Cantidad</th>
                            <th>Serie-Inicial</th>
                            <th>Serie-Final</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}