Apps/core/urls.py
from django.urls import path
from Apps.core.views.dashboard.views import DashboardView
from Apps.core.views.driver.views import  DriverListView, DriverCreateView, DriverDeleteView, DriverUpdateView
from Apps.core.views.ticket.views import TicketCreateView, TicketDeleteView, TicketListView, TicketUpdateView
from Apps.core.views.purchase.views import PurchaseCreateView, PurchaseListView, PurchaseDeleteView, PurchaseUpdateView

app_name = 'core'

urlpatterns = [
    # Home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    # Ticket
    path('ticket/list/', TicketListView.as_view(), name='ticket_list'),
    path('ticket/add/', TicketCreateView.as_view(), name='ticket_create'),
    path('ticket/update/<int:pk>/', TicketUpdateView.as_view(), name='ticket_update'),
    path('ticket/delete/<int:pk>/', TicketDeleteView.as_view(), name='ticket_delete'),

    # Driver
    path('driver/list/', DriverListView.as_view(), name='driver_list'),
    path('driver/add/', DriverCreateView.as_view(), name='driver_create'),
    path('driver/update/<int:pk>/', DriverUpdateView.as_view(), name='driver_update'),
    path('driver/delete/<int:pk>/', DriverDeleteView.as_view(), name='driver_delete'),

    # Purchase
    path('purchase/list/', PurchaseListView.as_view(), name='purchase_list'),
    path('purchase/add/', PurchaseCreateView.as_view(), name='purchase_create'),
    path('purchase/update/<int:pk>/', PurchaseUpdateView.as_view(), name='purchase_update'),
    path('purchase/delete/<int:pk>/', PurchaseDeleteView.as_view(), name='purchase_delete'),
]

Apps/security/urls.py
from django.urls import path

from Apps.security.views.dashboard.views import DashboardCreateOrUpdateView
from Apps.security.views.accessuser.views import AccessUserListView,AccessUserDeleteView
from Apps.security.views.auditdriver.views import AuditDriverListView
from Apps.security.views.auditpurchase.views import AuditPurchaseListView

app_name = 'security'

urlpatterns = [
    # Config Dashboard
    path('dashboard/update/', DashboardCreateOrUpdateView.as_view(), name='config_dashboard'),

    # Access Users
    path('access/list/', AccessUserListView.as_view(), name='accessuser_list'),
    path('access/delete/<int:pk>/', AccessUserDeleteView.as_view(), name='accessuser_delete'),

    # Audit Drivers
    path('driver/list/', AuditDriverListView.as_view(), name='audit_driver_list'),

    # Audit Purchases
    path('purchase/list/', AuditPurchaseListView.as_view(), name='audit_purchase_list'),
]

Apps/user/urls.py
from django.urls import path
from Apps.user.views import UserChangeGroup, UserChangePasswordView, UserCreateView, UserDeleteView, UserListView, UserProfileView, UserUpdateView

app_name = 'user'

urlpatterns = [
    # user
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
]

Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static

from Apps.security.views.dashboard.views import page_not_found404

urlpatterns = [
    path('', include('Apps.login.urls')),
    path('login/', include('Apps.login.urls')),
    path('menu/', include('Apps.core.urls')),
    path('user/', include('Apps.user.urls')),
    path('config/', include('Apps.security.urls')),
    path('admin/', admin.site.urls),
]

handler404 = page_not_found404

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/core/views/dashboard/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class DashboardView(LoginRequiredMixin,TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        # now = datetime.now().strftime('%Y-%m-%d')
        # create_purchases = Purchase.objects.filter(date_joined=now).count()
        # active_users = User.objects.all().count()
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Panel de administrador'
        # context['users'] = active_users
        # context['registro'] = create_purchases
        return context

Apps/security/views/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
# from django.utils.decorators import method_decorator
# from django.views.decorators.csrf import csrf_exempt
from django.views.generic import UpdateView

from Apps.security.mixins import ValidatePermissionRequiredMixin
from Apps.security.models import Dashboard
from Apps.security.forms import DashboardForm

class DashboardCreateOrUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Dashboard
    form_class = DashboardForm
    template_name = 'form.html'
    success_url = reverse_lazy('core:dashboard')
    permission_required = 'change_dashboard'
    url_redirect = success_url

    def get_object(self, queryset=None):
        obj, created = Dashboard.objects.get_or_create(id=1, defaults={
            'name': 'Sistema Web',
            'author': 'Dev',
            'interv_graph_barline' : 1,
            'grade_graph_circular': 360
        })
        return obj
    
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            form = self.get_form()
            if form.is_valid():
                form.save()
                data['success'] = True
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Configuración del Dashboard'
        context['entity'] = 'Dashboard'
        context['action'] = 'edit'
        context['list_url'] = self.success_url
        return context

def page_not_found404(request, exception):
    return render(request, '404.html')

templates/body.html
{% extends 'home.html' %}
{% load static %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <div id="global-preloader" class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="{% static 'img/logoweb.png' %}" alt="logoApp" height="60" width="60">
        </div>
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Sidebar -->
        {% include 'sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                   
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>

    {% if messages %}
        <div id="error-messages-body" style="display:none;">
            {% for message in messages %}
                <span class="error-messages-body">{{ message|escapejs}}</span>
            {% endfor %}
        </div>
    {% endif %}

    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        var errorMessages = '';
        var errorMessagesDiv = $('#error-messages-body');
        if (errorMessagesDiv.length > 0) {
            var errorMessages = '';
            errorMessagesDiv.find('.error-messages-body').each(function() {
                errorMessages += $(this).text() + '\n';
            });
            if (errorMessages) {
                alert_message({'title' : 'Error!', 'icon' : 'error', 'msg' : errorMessages, 'timer': 5000});
            }
        }
    </script>
    </body>
{% endblock %}

templates/dashboard.html
{% extends 'body.html' %}
{% load static %}
{% block head %}

    <script src="{% static 'lib/highcharts-8.1.2/highcharts.js' %}"></script>
    <script src="{% static 'lib/moment-2.30.1/moment.min.js' %}"></script>
    
{% endblock %}
{% block content %}
    <div class="card">
        <div class="card-header navbar-dark-blue">
            <h3 class="card-title fuente">
                <i class="fas fa-chart-bar"></i>
                Dashboard
            </h3>
        </div>
        <div class="card-body">
            <div id="dashboard-line" class="row" >
            </div>
            <div class="row" >
                <div id="dashboard-bar" class="col-lg-6 col-12">
                </div>
                <div id="dashboard-circle" class="col-lg-6 col-12">
                </div>
            </div>
            <div class="row" style="display: none;">
                <div class="col-lg-3 col-6">
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{ registro }}</h3>
                            <p>Registros Creados<br />Hoy</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-file-invoice"></i>
                        </div>
                        <a href="{% url 'core:purchase_list' %}" class="small-box-footer">Más Información<i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-6">
                    <div class="small-box bg-orange">
                        <div class="inner">
                            <h3>{{ users }}</h3>
                            <p>Usuarios<br />Creados</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-user-plus"></i>
                        </div>
                        <a href="{% url 'user:user_list' %}" class="small-box-footer">Más Información<i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        document.addEventListener('DOMContentLoaded', function() {
            var grade = '{{ dashboard.grade_graph_circular }}';
            var mingrade = 0;
            var maxgrade = 390;
            if (grade == 90) {
                mingrade = -90;
                maxgrade = 90;
            } else if (grade == 180) {
                mingrade = 0;
                maxgrade = 180;
            }

            function updateCharts(data) {
                Highcharts.chart('dashboard-line', {
                        chart: {
                            type: 'line'
                        },
                        title: {
                            text: 'Tendencia de Compras Mensuales en 2024'
                        },
                        xAxis: {
                            // categories: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 
                            //             'Agosto','Setiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                            categories: data.line_chart.months,
                            title: {
                                text: 'Mes'
                            }
                        },
                        yAxis: {
                            title: {
                                text: 'N° de Compras'
                            },
                            tickInterval: '{{ dashboard.interv_graph_barline }}',
                            min: 0
                        },
                        series: [{
                            name: 'Compras',
                            showInLegend: false,
                            colorByPoint: true,
                            data: data.line_chart.total_purchases
                        }],
                        credits:{
                            enabled: false
                        },
                        plotOptions:{
                            line:{
                                dataLabels: {
                                    enabled: true,
                                    format: '{point.y}'
                                },
                                enableMouseTracking: true
                            }
                        }
                    });
                Highcharts.chart('dashboard-bar', {
                    chart: {
                        type: 'column'
                    },
                    title: {
                        text: 'Total de Compras por Año'
                    },
                    xAxis: {
                        categories: data.bar_chart.years,
                        title: {
                            text: 'Año'
                        }
                    },
                    yAxis: {
                        title: {
                            text: 'N° de Compras'
                        },
                        tickInterval: '{{ dashboard.interv_graph_barline }}',
                        min: 0
                    },
                    series: [{
                        name: 'Compras',
                        showInLegend: false,
                        colorByPoint: true,
                        data: data.bar_chart.total_purchases
                    }],
                    credits:{
                        enabled: false
                    }
                });
                Highcharts.chart('dashboard-circle', {
                    chart: {
                        type: 'pie'
                    },
                    title: {
                        text: 'Distribución de compras por Chofer'
                    },
                    series: [{
                        name: 'Compras',
                        // data: ['Sebastian'].map((user, index) => ({
                        //     name: user,
                        //     y: [100, 40, 70, 150][index]
                        // })),
                        data: Object.entries(data.pie_chart.user_data).map(([chofer, total]) => ({ name: chofer, y: total }))
                    }],
                    credits:{
                        enabled: false
                    },
                    plotOptions:{
                        pie:{
                            dataLabels: {
                                enabled: true,
                                format: '{point.name} : ({point.percentage:.1f}%)'
                            },
                            startAngle: mingrade,
                            endAngle: maxgrade,
                            center: ['50%', '50%']
                        }
                    }
                });
            }

            const socket = new WebSocket('ws://' + host + '/ws/dashboard/');

            socket.onopen = function(e) {
                console.log('WebSocket conexión establecida.');
                var parameter = JSON.stringify({ 'action': 'get_data_graph' });
                socket.send(parameter );
                setInterval(function() {
                    socket.send(parameter);
                }, 10000); 
            };

            socket.onmessage = function(e) {
                const data = JSON.parse(e.data);
                updateCharts(data);
            };

            socket.onerror = function(e) {
                console.error('WebSocket error:', e);
            };

            socket.onclose = function(e) {
                console.log('WebSocket conexión cerrada.');
            };

        });
    </script>
{% endblock %}

templates/delete.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card">
            <div class="card-header navbar-dark-blue">
                <h3 class="card-title fuente"> 
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                <input type="hidden" name="action" value='{{ action }}'>
                <div class="alert alert-danger alert-dismissible">
                    <!-- <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> -->
                    <h5><i class="icon fas fa-ban"></i> Notificación</h5>
                    {% block messagedelete %}
                        Se va eliminar el registro N° "{{ object.id }}" de manera permanente.
                    {% endblock %}
                </div>
            </div>
            <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-flat btn-custom">
                        <i class="fas fa-save"></i> Sí, aceptar
                    </button>
                    <a href="{{ list_url }}" class="btn btn-danger btn-flat btn-custom">
                        <i class="fas fa-times"></i> Cancelar
                    </a>
            </div>
        </div>
    </form>
    {% if form.errors %}
        <div id="error-messages-delete" style="display:none;">
            {% for field in form %}
                {% for error in field.errors %}
                    <span class="error-messages-delete">{{ error|escapejs }} Campo: {{ field.label|escapejs }}</span>
                {% endfor %}
            {% endfor %}
        </div>
    {% endif %}
    <script>
        var errorMessages = '';
        var errorMessagesDiv = $('#error-messages-delete');
        if (errorMessagesDiv.length > 0) {
            var errorMessages = '';
            errorMessagesDiv.find('.error-messages-delete').each(function() {
                errorMessages += $(this).text() + '\n';
            });
            if (errorMessages) {
                alert_message({'title' : 'Error!', 'icon' : 'error', 'msg' : errorMessages, 'timer': 5000});
            }
        }

        $('form').on('submit', function(e){
            e.preventDefault();
            var parameters = new FormData(this);
            var btnsubmit = $(this).find('[type="submit"]').first();
            btnsubmit.prop('disabled', true);
            args = {
                'type': 'red',
                'url' : pathname,
                'parameters' : parameters,
                'btnsubmit' : btnsubmit,
                'success' : function (response) {
                    alert_message({'redirect': '{{ list_url }}'});
                }
            }
            submit_with_ajax(args);
        });
    </script>
{% endblock %}

templates/footer.html
<footer class="main-footer">
  <div class="float-right d-none d-sm-inline">
  </div>
  <strong><a href="#" Target="_blank" style='color: #0A4564;'>Copyright © 2024-{{ year }}</a>.</strong> Desarrollado por {{ dashboard.author }}.
</footer>

templates/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-dark-black">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
                <a href="{% url 'core:dashboard' %}" class="nav-link">Menú Principal</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if request.user.groups.all %}
            <li class="nav-item dropdown">
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0px; right: inherit;">
                        {% for g in request.user.groups.all %}
                            {% if g.id != request.session.group.id %}
                                <li><a href="{% url 'user:user_change_group' g.id %}"
                                       class="dropdown-item">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}

        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#" title="Perfil">
                <i class="fa-solid fa-user-lock"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header ">
                        Últ. acceso: {{ request.user.last_login }} 
                    </span>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:user_profile' %}" class="dropdown-item nav-link--inside changecolor">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:user_change_password' %}" class="dropdown-item nav-link--inside changecolor">
                    <i class="fas fa-lock mr-2"></i> Editar password
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}" title="Cerrar Sesión">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4 navbar-dark-black">
    <a href="{% url 'core:dashboard' %}" class="brand-link">
        <img src="{{ dashboard.get_logo }}"
             class="brand-image img-circle"
             style="opacity: .8">
        <span class="brand-text font-weight-light">{{ dashboard.name }}</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_image }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.get_full_name }}</a>
            </div>
        </div>
        <div class="form-inline">
          <div class="input-group" data-widget="sidebar-search">
            <input class="form-control form-control-sidebar" type="search" placeholder="Buscar" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-sidebar">
                <i class="fas fa-search fa-fw"></i>
              </button>
            </div>
          </div><div class="sidebar-search-results">
            <div class="list-group">
              <a href="#" class="list-group-item">
                <div class="search-title">
                  <strong class="text-light"></strong>E<strong class="text-light"></strong>l<strong class="text-light"></strong>e<strong class="text-light"></strong>m<strong class="text-light"></strong>e<strong class="text-light"></strong>n<strong class="text-light"></strong>t<strong class="text-light"></strong>o
                  <strong class="text-light"></strong>n<strong class="text-light"></strong>o
                  <strong class="text-light"></strong>e<strong class="text-light"></strong>n<strong class="text-light"></strong>c<strong class="text-light"></strong>o<strong class="text-light"></strong>n<strong class="text-light"></strong>t<strong class="text-light"></strong>r<strong class="text-light"></strong>a<strong class="text-light"></strong>d<strong class="text-light"></strong>o<strong class="text-light"></strong>!<strong class="text-light"></strong>
                </div>
              </a>
            </div>
          </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header"> Módulos</li>
                  <li class="nav-item">
                    <a href="#" class="nav-link  nav-link--inside">
                      <i class="nav-icon fa-solid fa-cart-shopping"></i>
                      <p>
                          Boletaje
                        <i class="right fas fa-angle-left"></i>
                      </p>
                    </a>
                    <ul class="nav nav-treeview">
                      <li class="nav-item">
                        <a href="{% url 'core:ticket_list' %}" class="nav-link nav-link--inside">
                          <i class="fa-solid fa-tags nav-icon"></i>
                          <p>Boletos</p>
                        </a>
                      </li>
                    </ul>
                    <ul class="nav nav-treeview">
                      <li class="nav-item">
                        <a href="{% url 'core:driver_list' %}" class="nav-link nav-link--inside">
                          <i class="fa-regular fa-id-card nav-icon"></i>
                          <p>Choferes</p>
                        </a>
                      </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                          <a href="{% url 'core:purchase_list' %}" class="nav-link nav-link--inside">
                            <i class="fas fa-file-invoice nav-icon"></i>
                            <p>Compras</p>
                          </a>
                      </li>
                    </ul>
                  </li>
                {% if request.session.group.name == 'Administrador'%}
                  <li class="nav-item">
                    <a href="#" class="nav-link nav-link--inside">
                      <i class="nav-icon fas fa-lock"></i>
                      <p>
                          Seguridad
                        <i class="right fas fa-angle-left"></i>
                      </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                          <a href="{% url 'user:user_list' %}" class="nav-link nav-link--inside">
                            <i class="fas fa-users-cog nav-icon"></i>
                            <p>Usuarios</p>
                          </a>
                       </li>
                    </ul>
                    <ul class="nav nav-treeview">
                      <li class="nav-item">
                        <a href="{% url 'security:accessuser_list' %}" class="nav-link nav-link--inside">
                          <i class="fa-solid fa-user-secret nav-icon"></i>
                          <p>Accesos</p>
                        </a>
                     </li>
                    </ul>
                    <ul class="nav nav-treeview">
                      <li class="nav-item">
                        <a href="#" class="nav-link nav-link--inside">
                          <i class="fa-solid fa-magnifying-glass nav-icon"></i>
                          <p>
                              Auditoría
                            <i class="right fas fa-angle-left"></i>
                          </p>
                        </a>
                        <ul class="nav nav-treeview">
                          <li class="nav-item">
                            <a href="{% url 'security:audit_driver_list' %}" class="nav-link nav-link--inside">
                              <i class="fa-regular fa-id-card nav-icon"></i>
                              <p>Choferes</p>
                            </a>
                         </li>
                        </ul>
                        <ul class="nav nav-treeview">
                          <li class="nav-item">
                            <a href="{% url 'security:audit_purchase_list' %}" class="nav-link nav-link--inside">
                              <i class="fas fa-file-invoice nav-icon"></i>
                              <p>Compras</p>
                            </a>
                         </li>
                        </ul>
                     </li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link nav-link--inside">
                      <i class="nav-icon fa-solid fa-gears"></i>
                      <p>
                          Configuración
                        <i class="right fas fa-angle-left"></i>
                      </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                          <a href="{% url 'security:config_dashboard' %}" class="nav-link nav-link--inside">
                            <i class="fa-solid fa-screwdriver-wrench nav-icon"></i>
                            <p>Dashboard</p>
                          </a>
                      </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                          <a href="/admin/" class="nav-link nav-link--inside">
                            <i class="fa-solid fa-solar-panel nav-icon"></i>
                            <p>Panel Administrador</p>
                          </a>
                      </li>
                    </ul>
                  </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</aside>